### ISSUE TITLE
for select usage error

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/opengemini-client-go#100]
https://github.com/openGemini/opengemini-client-go/blob/0a8ed4306924dcc311acda5517b0c920ea4a00a1/opengemini/write.go#L128-L149

Same error for ` for select`. Donot do function after select. It will be stack when signal income. And the behavior in next loop is unforeseeable

**Comment by wolfbolin** [comment]
#87

**Comment by cyruslo** [comment]
please assign this issue to me

**Comment by shoothzj** [comment]
closed by #136

**Comment by wolfbolin** [comment]
This PR #136  doesn't seem to have solved the problem.

**Comment by shoothzj** [comment]
After merging #136 and #141,  I believe the issue where the original context stops but the http request continues to execute has been fixed. We will continue to track the issue with callbacks potentially causing blocking tasks, leading to the Write coroutine being blocked, under #100.
Ofcourse, we recommend users avoid performing blocking operations within callbacks.
