### ISSUE TITLE
Error uses the common naming format

### ISSUE THREAD

**Issue by dream-kzx** [openGemini/opengemini-client-go#101]
https://github.com/openGemini/opengemini-client-go/blob/5898fcc3966deb7f364cf7eedbefcd6108c541fb/opengemini/servers_check.go#L10

Error uses the common naming format.
ErrAllServersDown or AllServersDownErr

**Comment by xuthus5** [comment]
in the style of go, it is better to use ErrXXX.

**Comment by shoothzj** [comment]
Thanks for your report, I would prefer ErrAllServersDown
