### ISSUE TITLE
Pre-allocate memory for slices to prevent repeated reallocation and copy during capacity expansion

### ISSUE THREAD

**Issue by dream-kzx** [openGemini/opengemini-client-go#103]
https://github.com/openGemini/opengemini-client-go/blob/5898fcc3966deb7f364cf7eedbefcd6108c541fb/opengemini/retention_policy.go#L81-L129

variable: retentionPolicy

**Comment by shoothzj** [comment]
Although query retention policy isn't performance sensitive, but I think it can be optimized. #102 also reveals another problems of this class method. cc @cyruslo @Chenxulin97

**Comment by dream-kzx** [comment]
There are many other places with the same problem. I've only listed this one.

**Comment by Chenxulin97** [comment]
> There are many other places with the same problem. I've only listed this one.

It's not a problem , we will find the whole places and fix them . thanx for ur contribution.

**Comment by dream-kzx** [comment]
ok

**Comment by shoothzj** [comment]
@dream-kzx Let's keep this issue open util it's resolved :)

**Comment by shoothzj** [comment]
closed by #117
