### ISSUE TITLE
需要检查BatchConfig.BatchSize 的上限值 避免创建管道造成内存溢出 fatal error

### ISSUE THREAD

**Issue by njbestway** [openGemini/opengemini-client-go#112]
在 client_impl.go 文件中的 newClient 方法，应该检查 c.BatchConfig.BatchSize 的上限值，此处已经做了下限值检查，缺少上限值检查，避免出现内存溢出，建议结合服务器端的默认bodySize参数等因素，合理设置默认值

        ////.......
       
	if c.BatchConfig != nil {
		if c.BatchConfig.BatchInterval <= 0 {
			return nil, errors.New("batch enabled, batch interval must be great than 0")
		}
		if c.BatchConfig.BatchSize <= 0 {
			return nil, errors.New("batch enabled, batch size must be great than 0")
		}
	}
        ////.......
当测试时传入 math.MaxInt32 作为BatchConfig.BatchSize 
没有deffer时报错
runtime: VirtualAlloc of 34359738368 bytes failed with errno=1455
fatal error: out of memory

当有deffer 时报错
panic: makechan: size out of range [recovered]
	panic: makechan: size out of range

以上测试可能会根据系统内存不同会有区别

**Comment by xuthus5** [comment]
I think the client program cannot get the optimal value of batch_size, so I added a detailed description of batch_size to reveal the impact if batch_size is too large.
