### ISSUE TITLE
Go mod version

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/opengemini-client-go#128]
The project's dependency library `github.com/prometheus/client_golang` requires golang to be at least 1.20. but the version stated in go.mod is 1.19.
Reference [https://github.com/prometheus/client_golang](https://github.com/prometheus/client_golang#:~:text=This%20library%20requires%20Go1.20%20or%20later.)

https://github.com/openGemini/opengemini-client-go/blob/4ade7de3d18867fcbbc6c4faada2e61f78b74708/go.mod#L3

At the same time, run example errors at go 1.19.6
![image](https://github.com/user-attachments/assets/5a9deeab-ddd7-46cc-8c4d-d4c22b751b77)

**Comment by shoothzj** [comment]
I am sure we need update to golang 1.20
