### ISSUE TITLE
Duplicate checking for query results

### ISSUE THREAD

**Issue by stormheng** [openGemini/opengemini-client-go#132]
https://github.com/openGemini/opengemini-client-go/blob/e15a322d7b9b723bcd406921aaae89964c144829/opengemini/retention_policy.go#L158-L164

The same checking is existed already in `queryResult.convertRetentionPolicy()`

**Comment by shoothzj** [comment]
Thanks for submitting this issue, would you want to fix this? :)

**Comment by shoothzj** [comment]
closed by #138
