### ISSUE TITLE
AuthType question

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/opengemini-client-go#134]
https://github.com/openGemini/opengemini-client-go/blob/e15a322d7b9b723bcd406921aaae89964c144829/opengemini/client.go#L9-L13

AuthTypeToken will be validated. But never be used.
Is this mode supported?

Referring to the documentation, should there be a None enum type here
https://github.com/openGemini/openGemini.github.io/blob/main/src/guide/develop/client_design.md#client-constructor-params-design

**Comment by shoothzj** [comment]
>> Referring to the documentation, should there be a None enum type here
https://github.com/openGemini/openGemini.github.io/blob/main/src/guide/develop/client_design.md#client-constructor-params-design

Sorry, I create a patch to fix the doc https://github.com/openGemini/openGemini.github.io/pull/121

It's intend to be
```
        + AuthConfig authConfig // nullable, if null, means no auth
        + BatchConfig batchConfig // nullable, if null, means batch is disabled
```

**Comment by shoothzj** [comment]
> AuthTypeToken will be validated. But never be used.
> Is this mode supported?

The server currently does not support the Token type, and the SDK implementation for Token is incomplete.
