### ISSUE TITLE
failed to create database like "demo-test" if "-" in db name

### ISSUE THREAD

**Issue by shilinlee** [openGemini/opengemini-client-go#44]
1. 
https://github.com/openGemini/opengemini-client-go/blob/40fd91311772c9bc3e8f80939a865d787d037bba/opengemini/database.go#L34-L34

2. 
https://github.com/openGemini/opengemini-client-go/blob/40fd91311772c9bc3e8f80939a865d787d037bba/opengemini/database.go#L88

failed to create database like "demo-test" if "-" in db name.

How to elegantly solve db names that require quotation marks and those that do not require quotation marks.

**Comment by shoothzj** [comment]
closed by #47
