### ISSUE TITLE
数据库异常时，此时继续写入数据会导致程序 panic 异常退出，原因是resp.Body 为 nil

### ISSUE THREAD

**Issue by njbestway** [openGemini/opengemini-client-go#79]
write.go  88行~94行代码如下：
       
        resp, err := c.innerWrite(database, &buffer)
	if err != nil {
		callback(errors.New("innerWrite request failed, error: " + err.Error())) 
               //建议直接  return err
	}

	defer resp.Body.Close()
      
      如果 innerWrite 返回err != nil，resp 有可能 为nil  导致程序 panic 异常退出

**Comment by Chenxulin97** [comment]
nice catch！这里确实存在问题，感谢你的issue。你有兴趣就此提交一个pr做修复吗？

**Comment by shoothzj** [comment]
Thanks for your contribution and welcome to the community. If there is no concerns, I think this issue can be closed, feel free to reopen it.

**Comment by Chenxulin97** [comment]
@njbestway  I sent u an email few days ago. could u plz reply it?
