### ISSUE TITLE
sdk should support write data into special retention policy

### ISSUE THREAD

**Issue by xiangyu5632** [openGemini/opengemini-client-go#80]
I want to discuss the functionality of our software development kit (SDK) that should allow developers to specify how long data should be retained within an application or service. This is a common requirement for applications that you can manage data with different retention policies.
openGemini has supported, but our SDK not

**Comment by Chenxulin97** [comment]
we will support write data into special retention policy in next release ：）

**Comment by shoothzj** [comment]
closed by #82
