### ISSUE TITLE
需要适配ipv6网络环境

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/opengemini-client-go#83]
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/client_impl.go#L86
应修改为
```
urls[i] = endpoint{url: protocol + net.JoinHostPort(addr.Host, strconv.Itoa(addr.Port))}
```

**Comment by Chenxulin97** [comment]
accept

**Comment by shoothzj** [comment]
Nice Catch! is this any possible we can find this by `golangci-lint`
