### ISSUE TITLE
重复使用的对象名

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/opengemini-client-go#84]
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/client_impl.go#L62

Declaration of 'client' shadows declaration at client_impl.go

**Comment by xuthus5** [comment]
this is not risky code, can you help optimize it?

**Comment by wolfbolin** [comment]
Fix by #110

**Comment by shoothzj** [comment]
closed by #110
