### ISSUE TITLE
config.TlsEnabled 配置歧义

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/opengemini-client-go#85]
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/client_impl.go#L90-L109

TLSClientConfig=nil 即可表示Tls关闭，无需根据TlsEnabled选择性创建Client对象
TlsEnabled=False config.TlsConfig=&tls.Config{InsecureSkipVerify: true} 时行为可能不符合预期

**Comment by xuthus5** [comment]
`config.TlsEnabled` controls the `Transport` and gives it a `tls.Config`. If TlsEnable is false, the `tls.Config` will not be passed to the Transport.
also, if TlsEnable is configured, but tls.Config is nil, we will continue to use TCP, which is a client configuration error, not the SDK.

**Comment by wolfbolin** [comment]
If I want use http connect, but http upgrade to https automatic. I need a config to skip verify.

**Comment by xuthus5** [comment]
services that can be upgraded to HTTPS services by the gateway or services are considered as HTTPS services ,cannot be configured as HTTP services on the client.

**Comment by wolfbolin** [comment]
> I think openGemini server doesn't support startTls yet.

If my openGemini server is working behind nginx or other reverse proxy server. It will behave differently than a directly connected service.

**Comment by shoothzj** [comment]
After invest to java,go,cpp code, I am considering to make tlsConfig optional in sdk's implement, so that we can remove tlsEnabled in go sdk @xuthus5 @hiiiik
