### ISSUE TITLE
网络请求无法终止

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/opengemini-client-go#89]
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/client_impl.go#L74-L77

Close()函数调用时，请求无法立刻终止，与期望行为不符。

**Comment by xuthus5** [comment]
should rewrite `http.NewRequestWithContext` or add `(*Request).WithContext`. @Chenxulin97 
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/http.go#L80

**Comment by shoothzj** [comment]
I think it's ok to keep the behavior now. Currently it's no guarantee the request will be suspended. It's not a simple mapping to http request(otherwise we can expose context in every method). Feel free to reopen this issue if you have other thoughts.

**Comment by wolfbolin** [comment]
The SDK does not provide a feasible way to terminate long unanswered HTTP requests. This can lead to a lot of goroutine leaks. Same problem in #87 

It is not reasonable to just configure a timeout parameter, as this can be very long.

The best way to control the lifecycle of an HTTP request is to use the context feature throughout the request.
Or for consistency in function signatures, you can add a timeout parameter for each method in the function.

**Comment by wolfbolin** [comment]
@shoothzj Pls reopen this issue. I'm sure this is a common problem in user habits.
