### ISSUE TITLE
code style problem

### ISSUE THREAD

**Issue by YH-Wang000** [openGemini/opengemini-client-go#91]
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/point.go#L81

代码风格更像java而不是go，可导出变量的赋值推荐使用字面量，使用也建议直接使用

**Comment by shoothzj** [comment]
Is there any offical docs or sample codes related to this?

**Comment by YH-Wang000** [comment]
https://go.dev/doc/effective_go，search keyword ”setter“ in web page

**Comment by shoothzj** [comment]
@YH-Wang000 make sense, Would you be willing to assist in fixing this issue?
