### ISSUE TITLE
http body未关闭

### ISSUE THREAD

**Issue by dream-kzx** [openGemini/opengemini-client-go#92]
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/ping.go#L11-L22

http body未关闭，资源泄露，问题很严重

**Comment by Chenxulin97** [comment]
accpet

**Comment by shoothzj** [comment]
Nice Catch! Can you help send a PR to fix this problem?
