### ISSUE TITLE
updateAuthHeader函数返回值优化

### ISSUE THREAD

**Issue by wolfbolin** [openGemini/opengemini-client-go#93]
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/http.go#L28-L30

header==nil 的检查建议放在函数首行，避免函数返回值可能为nil，减少后续代码出错的可能

**Comment by shoothzj** [comment]
I think it's intend to avoid allocate when header is nil and no-auth required, but I think we can add unit test to cover that
