### ISSUE TITLE
尽可能减少断言调用，降低开销

### ISSUE THREAD

**Issue by dream-kzx** [openGemini/opengemini-client-go#94]
https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/query.go#L112-L117

这里断言2次，实际断言1次即可。断言在go中是一个开销比较高的操作

**Comment by Chenxulin97** [comment]
accept

**Comment by shoothzj** [comment]
Nice Catch!

**Comment by shoothzj** [comment]
Can you please help send a pr to fix it?

**Comment by shoothzj** [comment]
closed by #107
