### ISSUE TITLE
secret: math/rand a weakly random and thread-unsafe library

### ISSUE THREAD

**Issue by xuthus5** [openGemini/opengemini-client-go#96]
NewSource returns a new pseudo-random [Source] seeded with the given value, Unlike the default [Source] used by top-level functions, this source is not safe for concurrent use by multiple goroutines.

https://github.com/openGemini/opengemini-client-go/blob/49423902a3ca16ac35fa57265f70914d470a964d/opengemini/random_util.go#L9

Use of weak random number generator,  math/rand or math/rand/v2 instead of crypto/rand

**Comment by shoothzj** [comment]
IIUC, this is only used in test files. PRs are welcome.
